### ISSUE TITLE
SyntaxError: C:/Users/__/myapp/myapp/gulpfile.babel.js: "gulp" is read-only

### ISSUE THREAD

**Issue by YoavRheims** [babel/gulp-babel#109]
Hi,

I just understand how to fix this issue: 
`C:\Users\Yoav\myapp\myapp>gulp critcal
[10:39:41] Requiring external module babel-register
C:\Users\Yoav\myapp\myapp\node_modules\babel-core\lib\transformation\file\index.js:600
      throw err;
      ^

SyntaxError: C:/Users/Yoav/myapp/myapp/gulpfile.babel.js: "gulp" is read-only
  1 |
 2 | var gulp = require('gulp');
    |     ^
  3 | var gutil = require('gulp-util');
  4 | var critical = require('critical').stream;
  5 |
    at File.buildCodeFrameError (C:\Users\Yoav\myapp\myapp\node_modules\babel-core\lib\transformation\file\index.js:431:15)
    at NodePath.buildCodeFrameError (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\path\index.js:140:26)
    at PluginPass.Scope (C:\Users\Yoav\myapp\myapp\node_modules\babel-plugin-check-es2015-constants\lib\index.js:35:29)
    at PluginPass.newFn (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\visitors.js:318:17)
    at newFn (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\Users\Yoav\myapp\myapp\node_modules\babel-traverse\lib\context.js:192:19)`

**Comment by YoavRheims** [comment]
I tried to clean npm cache, uninstall and reinstall. Nothing helped.

**Comment by loganfsmyth** [comment]
I think we'd have to see your `gulpfile.babel.js` to know what is wrong. It sounds like you're assigning to your `gulp` variable, but since it is a `var` in the output that is a little confusing.

**Comment by YoavRheims** [comment]
I followed these steps: https://github.com/addyosmani/critical
Dunno what I didn't do right.

**Comment by loganfsmyth** [comment]
As I said, we'll need to see your gulpfile.

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
