### ISSUE TITLE
presets Error

### ISSUE THREAD

**Issue by DavidTorrijos** [babel/gulp-babel#120]
Hi guys!
I have problems to compile my es6 code.

I recibe this error from my gulpfile.js:

**events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module 'lodash/isPlainObject' (While processing preset: "/Users/david/node_modules/babel-preset-es2015/lib/index.js")
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/david/node_modules/babel-types/lib/converters.js:27:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)**

The error appear when I use presets on my task.
The code on my gulpfile.js is the next one:

```
const gulp = require('gulp');
const babel = require('gulp-babel');

gulp.task('default', () => {
  return gulp.src('../../sources/es6/style.js')
    .pipe(babel({
      presets: ['es2015']
    }))
    .pipe(gulp.dest('../../app/javascripts'));
});
```

I have included in my package.json at devDependences the necessary dependences with:
`npm install --save-dev gulp-babel babel-preset-es2015`

Gulp, Gulp CLI, node... everything is updated and works properly but when I include the next pipe the error appear:
```
.pipe(babel({
  presets: ['es2015']
}))
```

I trying to include the presets in a .babelrc file and in my package.json, but nothing...

Thank you so much!

**Comment by DavidTorrijos** [comment]
Hey guys!
Everything fine, the problem was in: return gulp.src('../../sources/es6/style.js')
if I write a route for the files at same level like: return gulp.src('sources/es6/style.js'), the task works properly.

I close the issue, Thank you!
