### ISSUE TITLE
当我引入gulp-babel报错

### ISSUE THREAD

**Issue by 13653389794** [babel/gulp-babel#139]
我的gulpfile
```
const gulp = require('gulp');
const babel = require('gulp-babel');
const browserSync = require('browser-sync').create(); 
const runSequence = require('run-sequence'); 

gulp.task('js', function(){
	gulp.src('src/**/*.js')
		// .pipe(babel({
  //           presets: ['@babel/env']
  //       }))
        .pipe(gulp.dest('dist'))
})
gulp.task('html', function(){
	gulp.src('src/**/*.html')
        .pipe(gulp.dest('dist'))
})
gulp.task('reload', function () {
    browserSync.reload('dist');
}) 

gulp.task('server', function () {
    browserSync.init({
        server: 'dist',
    });
    gulp.watch('src/**').on('change', function () {
        runSequence(["html","js"], "reload");
    });
});

gulp.task('default',function(){
    runSequence(["html",'js'], "server");
})`
我的package 
{
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.37",
    "@babel/preset-env": "^7.0.0-beta.37",
    "browser-sync": "^2.23.3",
    "gulp-babel": "^7.0.0"
  },
  "dependencies": {
    "lodash": "^4.17.4",
    "run-sequence": "^2.2.1"
  }
}
当我执行gulp时候报的错
module.js:529
    throw err;
    ^

Error: Cannot find module 'lodash/cloneDeep'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/apple/node_modules/.6.24.1@babel-template/lib/index.js:57:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by demurgos** [comment]
Please report your issues in english and use fenced code blocks for formatting (using 3 backticks <code>```</code> before and after the code).

Your error is related to your package manager and the `babel-template` package, not to `gulp-babel`.
