### ISSUE TITLE
Error: Cannot find module '@babel/plugin-minify-dead-code-elimination'

### ISSUE THREAD

**Issue by tifDev** [babel/gulp-babel#171]
I've installed babel via:
`npm install --save-dev gulp-babel@7 babel-core babel-preset-env`

Then i also installed the plugins:
```
npm install babel-plugin-minify-dead-code-elimination --save-dev
npm install babel-plugin-transform-remove-console --save-dev
```

Here is my gulpFile.js:

```
const babel = require( 'gulp-babel' );

gulp.task( 'goBabel', () =>
    gulp.src( stage3 + 'all.js' )
    .pipe( babel( {
        presets: [ '@babel/env' ],
        plugins: [
                [ require( "@babel/plugin-minify-dead-code-elimination" ), { loose: true } ],
                require( "@babel/plugin-transform-remove-console" )
        ]
    } ) )
    .pipe( gulp.dest( stage1 ) )
);
```

When i run gulp goBabel im getting:
```
[23:06:31] Starting 'goBabel'...
[23:06:31] 'goBabel' errored after 11 ms
[23:06:31] Error: Cannot find module '@babel/plugin-minify-dead-code-elimination'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**How can i make this working?**

**Comment by loganfsmyth** [comment]
If you've installed `babel-plugin-minify-dead-code-elimination` and `babel-preset-env` for Babel 6, then those are what you should reference in your config. The `@babel/`-prefixed packages are for Babel >= 7.x
