### ISSUE TITLE
events.js:72 Gulp breaks preprocessing showing very strange error

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [babel/gulp-babel#20]
I have a file and babel worked there fine, but something happened and it stopped preprocessing. it started throwing an error:

```
events.js:72
        throw er; // Unhandled 'error' event
```

I went to google and asked and was given with this solution [link](http://stackoverflow.com/questions/24011349/gulp-error-events-js72).

Now it shows me these info:
```
Starting 'default'...
ReferenceError in plugin 'gulp-babel'
Message:
    path.../PersCrit/PersCrit_dev.js: Currency is not defined
Details:
    _babel: true
    fileName: path...\PersCrit\PersCrit_dev.js
[14:57:40] Finished 'default' after 25 ms
```

Gulpfile
```
var gulp = require('gulp');
var babel = require('gulp-babel');
var watch = require('gulp-watch');
var cache = require('gulp-cache');
var rename = require("gulp-rename");

// Handle the error
function errorHandler (error) {
  console.log(error.toString());
  this.emit('end');
}

gulp.task('clear', function (done) {
  return cache.clearAll(done);
});

gulp.task('default', function () {
  return gulp.src('PersCrit_dev.js')
    .pipe(watch('PersCrit_dev.js')).on('error', errorHandler)
    .pipe(babel()).on('error', errorHandler)
    .pipe(rename({
      basename: "PersCrit"
    })).on('error', errorHandler)
    .pipe(gulp.dest('path...'));
});
```
While the project itself on tab "Try it out" works fine.

Could you help me?

**Comment by sebmck** [comment]
No idea where that error is coming from but it's not [gulp-babel](https://github.com/babel/gulp-babel/search?utf8=%E2%9C%93&q=Currency).

**Comment by AlexanderTserkovniy** [comment]
Here is full trace of previous version without error handling:

```

events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: path...PersCrit/PersCrit_dev.js: Currency is not defined
    at finishNode (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2196:7)
    at parseEmptyStatement (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2866:12)
    at parseStatement (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2614:24)
    at parseTopLevel (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2567:18)
    at Object.exports.parse (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:51:12)
    at module.exports (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\lib\babel\helpers\parse.js:18:21)
    at File.<anonymous> (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\file.js:395:12)
    at File.parse (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\file.js:377:21)
    at Object.transform (path...PersCrit\node_modules\gulp-babel\node_modules\babel-core\lib\babel\transformation\index.js:19:15)
    at DestroyableTransform._transform (path...PersCrit\node_modules\gulp-babel\index.js:29:20)
    at DestroyableTransform.Transform._read (path...PersCrit\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (path...PersCrit\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (path...PersCrit\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (path...PersCrit\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (path...PersCrit\node_modules\gulp-babel\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (path...PersCrit\node_modules\gulp-watch\node_modules\readable-stream\lib\_stream_readable.js:623:24)

Process finished with exit code 8
```

In the last link, which is `node_modules\gulp-babel\node_modules\babel-core\node_modules\acorn-babel\acorn_csp.js:2196:7)` it this function:

```
// Finish an AST node, adding `type` and `end` properties.

  function finishNode(node, type) {
    node.type = type;
    node.end = lastEnd;
    if (options.locations)
      node.loc.end = lastEndLoc;
    if (options.ranges)
      Currency.range[1] = lastEnd;
    return node;
  }
```

**Comment by sebmck** [comment]
Something's messing with the source of `acorn_csp.js` as the verison on npm definently doesn't have that.

```sh
$ cat node_modules/acorn-babel/acorn_csp.js | grep Currency
$
```

**Comment by AlexanderTserkovniy** [comment]
```
$ cat node_modules/gulp-babel/node_modules/babel-core/node_modules/acorn-babel/
acorn_csp.js | grep Currency
      Currency.range[1] = lastEnd;
      Currency.range[1] = pos;
```

**Comment by sebmck** [comment]
Try reinstalling `gulp-babel`. `$ rm-rf node_modules && npm install`. Did you accidently do a search and replace on your entire `node_modules` directory? Otherwise it doesn't make much sense as that definently isn't in the npm release.

**Comment by AlexanderTserkovniy** [comment]
Try reinstalling `gulp-babel`, helped.
Thanks!
