### ISSUE TITLE
Stream doesn't have `on`

### ISSUE THREAD

**Issue by barneycarroll** [babel/gulp-babel#21]
I'm using gulp babel with sourcemaps pretty much as indicated by the README:

```javascript
var sync       = require( 'browser-sync' );
var gulp       = require( 'gulp' );
var sourcemaps = require( 'gulp-sourcemaps' );
var babel      = require( 'gulp-babel' );
var concat     = require( 'gulp-concat' );

gulp.task( 'compile', function(){
	gulp.src( 'src/**/*.js' )
		.pipe( sourcemaps.init() )
		.pipe( concat( 'src/js/index.js' ) )
		.pipe( babel() )
		.pipe( sourcemaps.write( '.' ) )
		.pipe( gulp.dest( 'app' ) )
		.pipe( sync.reload );
} );

gulp.task( 'serve', function(){
	sync( { server: './app' } );

	gulp.watch( 'src/**/*.*', [ 'compile' ] );
} );

gulp.task( 'default', [ 'compile', 'serve' ] );

```

Everything is compiled and mapped as I desire, but the `compile` task ends violently:

```log
$ gulp
[15:15:29] Using gulpfile ~/Documents/git/ithildin/gulpfile.js
[15:15:29] Starting 'compile'...
[15:15:29] 'compile' errored after 7.7 ms
[15:15:29] TypeError: Object function () {
        var args = Array.prototype.slice.call(arguments);
        if (singleton) {
            return singleton[name].apply(singleton, args);
        } else {
            if (name === "reload" && args[0] && args[0].stream) {
                return utils.noopStream();
            }
        }
    } has no method 'on'
    at DestroyableTransform.Stream.pipe (stream.js:65:8)
    at Gulp.gulp.task.sync.server (/Users/barney/Documents/git/ithildin/gulpfile.js:16:4)
    at module.exports (/Users/barney/Documents/git/ithildin/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/barney/Documents/git/ithildin/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/barney/Documents/git/ithildin/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/barney/Documents/git/ithildin/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
```

Any ideas?

**Comment by sebmck** [comment]
The error is coming from your `serve` gulp task and from most likely the `sync` call which is completely unrelated to `gulp-babel`.

**Comment by barneycarroll** [comment]
But the log is specifically telling me that the `compile` task errored. It doesn't even get to `serve`…

**Comment by sebmck** [comment]
```
at Gulp.gulp.task.sync.server (/Users/barney/Documents/git/ithildin/gulpfile.js:16:4)
```

**Comment by barneycarroll** [comment]
:O weeeird. Well-spotted, thanks. I'll post back when I've tracked this down.
