### ISSUE TITLE
docs don't say anything about where to place the babel config

### ISSUE THREAD

**Issue by mgenev** [babel/gulp-babel#35]
I want to add some optional flags like `bluebirdCoroutines`, but the docs don't make it obvious how to.
using `babel().transform("code", { optional: ["bluebirdCoroutines"] })`  like the normal library, results in `undefined is not a function`.

**Comment by mgenev** [comment]
OK, I saw the options bit, doh, which implies this should work:
`        .pipe(babel({optional: ['es7.asyncFunctions']}))` 
but it doesn't...
I still get

```
Users/mgenev1271/Projects/ape-poll-service/lib/handlers/poll/questions.js:21
            handler: async function(request, reply) {
                           ^^^^^^^^
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mgenev1271/Projects/ape-poll-service/lib/handlers/index.js:8:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)```
