### ISSUE TITLE
file.isNull() -> TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by Olgagr** [babel/gulp-babel#43]
I'm trying to use gulp-babel but I'm getting this error:

```
/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/index.js:13
		if (file.isNull()) {
		         ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/index.js:13:12)
    at DestroyableTransform.Transform._read (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/apple/Documents/learning/react/flux/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at DuplexWrapper._write (/Users/apple/Documents/learning/react/flux/node_modules/browserify/node_modules/duplexer2/index.js:57:18)
    at doWrite (/Users/apple/Documents/learning/react/flux/node_modules/browserify/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/Users/apple/Documents/learning/react/flux/node_modules/browserify/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at DuplexWrapper.Writable.write (/Users/apple/Documents/learning/react/flux/node_modules/browserify/node_modules/duplexer2/node_modules/readable-stream/lib/_stream_writable.js:211:11)

```

My gulp task look like this:

```
var gulp        = require('gulp'),
    $               = require('gulp-load-plugins')({lazy:true}),
    source      = require('vinyl-source-stream'),
    browserify = require('browserify');

gulp.task('scripts', function() {

  return browserify({
    entries: 'src/js/main.js',
    debug: true
  })
  .transform($.babel)
  .bundle()
  .pipe(source('main.js'))
  .pipe(gulp.dest('dist/js'))

});
```

My gulp version is 3.9.0.

**Comment by Olgagr** [comment]
Sure enough, I have to user babelify instead of gulp-babel to make it work with browserify.

**Comment by dalanmiller** [comment]
@Olgagr What is the difference between the two?

**Comment by Olgagr** [comment]
@dalanmiller In my case it was connecting together browserify + babel transformation. If you need to connect the two, you have to use babelify, not gulp-babel. Here is the gist with gulp task I finally use:

https://gist.github.com/Olgagr/e3efacebc74205ff898b

As you can see, I use there also watchify. It adds catching to speed up the task.
