### ISSUE TITLE
Error while parsing JSON

### ISSUE THREAD

**Issue by azat-io** [babel/gulp-babel#44]
Hello.

Could you help me with this simple question. All of my projects locate in ```/home/azat/git/```. For example if my project name is ```project``` it is in ```/home/azat/git/project``` folder.

In the ```project``` folder there are ```gulpfile.js```, ```package.json``` files and ```node_modules``` folder with npm packages.

Here is a part of my **gulfile.js**:

```js
var babel = require('gulp-babel');
var gulp = require('gulp');
var rename = require("gulp-rename");

gulp.task('jsx', function () {
  return gulp.src('src/jsx/*.jsx')
    .pipe(rename(function (path) {
      path.extname = ".js"
      }))
    .pipe(babel())
    .pipe(gulp.dest('src/js/'));
});
```

But if I put command ```gulp jsx```, terminal gives an error:

```bash
azat@pc:~/git/project$ gulp jsx
[11:12:36] Using gulpfile ~/git/project/gulpfile.js
[11:12:36] Starting 'jsx'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: /home/azat/git/package.json: Error while parsing JSON - Unexpected end of input
    at Object.parse (native)
    at OptionManager.addConfig (/home/azat/git/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:100:62)
    at OptionManager.findConfigs (/home/azat/git/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:171:32)
    at OptionManager.init (/home/azat/git/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/azat/git/project/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/azat/git/project/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/azat/git/project/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at DestroyableTransform._transform (/home/azat/git/project/node_modules/gulp-babel/index.js:30:20)
    at DestroyableTransform.Transform._read (/home/azat/git/project/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/home/azat/git/project/node_modules/gulp-babel/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
```

So, why ```gulp-babel``` search my ```package.json``` file in the ```/home/azat/git/``` folder? And how can I solve this problem?

**Comment by azat-io** [comment]
I found the solution of the problem. It was ```package.json``` in the ```/home/azat/git/``` folder, which is not my project folder. So, this is strange mistake.
