### ISSUE TITLE
throws on error + weird output

### ISSUE THREAD

**Issue by dwelle** [babel/gulp-babel#57]
similar to #20, re-install didn't help. `babel-cli` works fine so I figure it might be connected to `gulp-babel`.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: /static/src/js/spa.util.js: "test" is read-only
←[0m  1 | ←[36mconst←[39m test ←[1m=←[22m ←[35m42←[39m←[1m;←[22m
> 2 | test ←[1m=←[22m ←[35m100←[39m←[1m;←[22m
    | ^
  3 | ←[0m
    at File.buildCodeFrameError (\node_modules\gulp-babel\node_modules\babel-core\lib\transformation\file\index.js:408:15)
    at NodePath.buildCodeFrameError (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\path\index.js:150:26)
    at PluginPass.Scope (\node_modules\babel-preset-es2015\node_modules\babel-plugin-check-es2015-constants\lib\index.js:33:29)
    at PluginPass.newFn (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:311:17)
    at newFn (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\visitors.js:278:19)
    at NodePath._call (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\path\context.js:106:12)
    at TraversalContext.visitQueue (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:155:16)
    at TraversalContext.visitSingle (\node_modules\gulp-babel\node_modules\babel-core\node_modules\babel-traverse\lib\context.js:115:19)
```

gulpfile:

```
const gulp = require("gulp");
const babel = require("gulp-babel");

gulp.task( "default", () => {

    gulp.src("static/src/js/**/*.js")
        .pipe(babel({
            presets: ["es2015"]
        }))
        .pipe(gulp.dest("static/dest/js/"))
});
```

babel-cli output is ok:

```
$ babel static/src/js/spa.util.js --presets es2015
SyntaxError: static/src/js/spa.util.js: "test" is read-only
  1 | const test = 42;
> 2 | test = 100;
    | ^
  3 |
```

gulp version:

```
CLI version 3.9.0
Local version 3.9.0
```

babel-cli `v6.1.18 (babel-core 6.1.21)`, gulp-babel `6.1.0`

Windows 7, node `v4.2.1`

**Comment by laurelnaiad** [comment]
Something like this will get you a better error report: 

```
      .pipe(gulpBabel(this._babelOptions).on('error', (err) => {
        // we get an object that doesn't have a good toString()
        // implementation
        // We'll write it out similarly to how gulp-typescript writes
        // them

        console.log(
          chalk.red(
            err.fileName +
            (
                err.loc ?
                '(' + err.loc.line + ',' + err.loc.column + '): ' :
                ': '
            )
          ) +
          'error Babel: ' + err.message + '\n' +
          err.codeFrame
        );
      }))
      // etc
      .pipe(gulpSourcemaps.write(this._sourceMapsWriteOptions));
```

**Comment by hzoo** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or leave a comment asking to reopen this issue. Thanks! ✌️

> If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
