### ISSUE TITLE
ReferenceError: [BABEL] Unknown option: base.preset

### ISSUE THREAD

**Issue by Voyga** [babel/gulp-babel#71]
Error when executing gulp babel:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
ReferenceError: [BABEL] www/js/a.js: Unknown option: base.preset
    at Logger.error (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/Users/Voyga/Projects/HackPlan/One/code/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at DestroyableTransform._transform (/Users/Voyga/Projects/HackPlan/One/code/node_modules/gulp-babel/index.js:32:20)
    at DestroyableTransform.Transform._read (/Users/Voyga/Projects/HackPlan/One/code/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/Voyga/Projects/HackPlan/One/code/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/Voyga/Projects/HackPlan/One/code/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:335:12)
```

My gulp babel function:
```javascript
return gulp.src("www/js/a.js")
    .pipe(babel({
        preset: ["es2015"]
    }))
    .pipe(gulp.dest("www/dist"));
```

My node version is `5.4.0`

**Comment by Voyga** [comment]
Solved... I it's `presets` not `preset`... Sorry

**Comment by loganfsmyth** [comment]
No problem. In the future, please direct questions to Babel's support channels, listed in our main README.
