### ISSUE TITLE
Babili preset is not working

### ISSUE THREAD

**Issue by navarroaxel** [babel/gulp-babel#96]
I have been used gulp-babel with this config:

````javascript
gulp.src('index.html'])
        .pipe(useref())
        .pipe(gulpif('*.js', babel({compact: true})))
        .pipe(gulpif(['js/*.js', 'css/app.css'], gulp.dest('dist/public')))
````
and works fine. But, I have tried to use [babili](http://babeljs.io/blog/2016/08/30/babili)

````shell
$ npm install babel-preset-babili --save-dev
````

With this change in the config:

````javascript
        .pipe(gulpif('*.js', babel({presets: ['babili']})))
````

and, I'm getting this error:

````shell
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Plugin 0 specified in "foreign" provided an invalid property of "name"
    at Plugin.init (D:\Sources\gpss\node_modules\babel-core\lib\transformation\plugin.js:138:13)
    at Function.normalisePlugin (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:147:12)
    at D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:153:20)
    at OptionManager.mergeOptions (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:245:36)
    at D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:289:14
    at D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:342:20
    at Array.map (native)
    at OptionManager.resolvePresets (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:305:20)
    at OptionManager.mergePresets (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:288:10)
    at OptionManager.mergeOptions (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:14)
    at OptionManager.init (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\options\option-manager.js:383:12)
    at File.initOptions (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\index.js:223:65)
    at new File (D:\Sources\gpss\node_modules\babel-core\lib\transformation\file\index.js:140:24)
    at Pipeline.transform (D:\Sources\gpss\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
````

What I'm doing wrong? I develop for Chrome, and I want the final code with arrow functions and string templates minified.

**Comment by hzoo** [comment]
Can you update your babel packages? it needs a later version of babel-core

**Comment by navarroaxel** [comment]
These are the babel's packages what I use:
````JSON
"devDependencies": {
    "babel-preset-babili": "0.0.2",
    "gulp-babel": "^6.1.2",
}
````
I was using babel-core@6.13 I had manually update to version 6.14 and now works.
Thanks!

**Comment by hzoo** [comment]
We'd like to add an error to use 6.14 but I don't think we figured out how to do it correctly yet (I don't think a peerDep works either)\

awesome
